version: "3.9"
services:
  master:
    image: "redis:6.2.6"
    restart: always
    container_name: "master"
    volumes:
      - "./config:/etc/redis-config"
    command: ["redis-server","/etc/redis-config/redis-master.conf"]
    environment:
      TZ: Asia/Shanghai
    expose:
      - "6379"
  slave1:
    image: "redis:6.2.6"
    restart: always
    container_name: "slave1"
    volumes:
      - "./config:/etc/redis-config"
    command: ["redis-server","/etc/redis-config/redis-slave.conf"]
    environment:
      TZ: Asia/Shanghai
    expose:
      - "6379"
    depends_on:
      - master
  slave2:
    image: "redis:6.2.6"
    restart: always
    container_name: "slave2"
    volumes:
      - "./config:/etc/redis-config"
    command: ["redis-server","/etc/redis-config/redis-slave.conf"]
    environment:
      TZ: Asia/Shanghai
    expose:
      - "6379"
    depends_on:
      - master
  sentinel1:
    image: "redis:6.2.6"
    restart: always
    container_name: "sentinel1"
    volumes:
      - "./config:/etc/redis-config"
    command: ["redis-server","/etc/redis-config/redis-sentinel1.conf","--sentinel"]
    environment:
      TZ: Asia/Shanghai
    expose:
      - "26379"
    depends_on:
      - master
      - slave1
      - slave2
  sentinel2:
    image: "redis:6.2.6"
    restart: always
    container_name: "sentinel2"
    volumes:
      - "./config:/etc/redis-config"
    command: ["redis-server","/etc/redis-config/redis-sentinel2.conf","--sentinel"]
    environment:
      TZ: Asia/Shanghai
    expose:
      - "26379"
    depends_on:
      - master
      - slave1
      - slave2
  sentinel3:
    image: "redis:6.2.6"
    restart: always
    container_name: "sentinel3"
    volumes:
      - "./config:/etc/redis-config"
    command: ["redis-server","/etc/redis-config/redis-sentinel3.conf","--sentinel"]
    environment:
      TZ: Asia/Shanghai
    expose:
      - "26379"
    depends_on:
      - master
      - slave1
      - slave2