version: "3.9"
services:
  standalone:
    image: "redis:6.2.6"
    restart: always
    container_name: "standalone"
    volumes:
      - "./config:/etc/redis-config"
    command: ["redis-server","/etc/redis-config/redis.conf"]
    environment:
      TZ: Asia/Shanghai
    expose:
      - "6379"
  maven:
    image: "maven:3.8.5-jdk-8-slim"
    volumes:
      - "./wait:/wait"
      - "maven-repo:/root/.m2"
      - "../../:/usr/src/maven"
    working_dir: /usr/src/maven
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: standalone:6379
    command: sh -c "/wait && mvn test -Dstandalone"
volumes:
  maven-repo: